const host = require("../host");

const recipesList = [
  {
    id: 12321,
    img: "",
    createdUserId: null,
    name: "Борщ",
    likes: 5,
    level: "hard",
    compositionBase: ["Мясной бульйон", "Свекла", "Капуста", "Лук", "Картошка"],
    likesVisible: false,
    image: `${host}/images/borsh.jpeg`,
    userIdLiked: [959595],
  },
  {
    id: 728478,
    img: "",
    createdUserId: null,
    name: "Макароны по флотски",
    likes: 3,
    level: "medium",
    compositionBase: [
      "Сухие макароны",
      "Фарш(говяжий + свиной)",
      "Лук",
      "Морковь",
      "Специи",
    ],
    likesVisible: false,
    image: `${host}/images/pasta.jpeg`,
    userIdLiked: [],
  },
  {
    id: 43243242,
    img: "",
    createdUserId: null,
    name: "Яищница",
    likes: 4,
    level: "easy",
    compositionBase: ["Яйца", "Молоко"],
    likesVisible: false,
    image: `${host}/images/eggs.jpeg`,
    userIdLiked: [939393],
  },
  {
    id: 7457845,
    img: "",
    createdUserId: null,
    name: "Плов",
    likes: 4,
    level: "hard",
    compositionBase: ["Рис", "Баранина", "Морковь"],
    likesVisible: false,
    image: `${host}/images/plov.jpeg`,
    userIdLiked: [],
  },
  {
    id: 4312934,
    img: "",
    createdUserId: null,
    name: "Мясо по французки",
    likes: 4,
    level: "hard",
    compositionBase: ["Мясо(говяжье)", "Лук", "Морковь", "Картошка"],
    likesVisible: false,
    image: `${host}/images/meat.jpeg`,
    userIdLiked: [],
  },
];

module.exports = recipesList;
